version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.10
  - dependency-name: ember-cli
    versions:
    - 3.26.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  commit-message:
    prefix: "[skip netlify]"
